[tool.briefcase]
project_name = "FaceMole"
bundle = "de.danielaboeing"
version = "0.0.1"
url = "https://danielaboeing.de/facemole"
license = "BSD license"
author = 'Daniela Böing'
author_email = "daniela.boeing@hs-bochum.de"

[tool.briefcase.app.facemole]
formal_name = "FaceMole"
description = "App project for Hochschule Bochum, Master Computer Sciences"
icon = "src/facemole/resources/facemole"
sources = ['src/facemole']
requires = []


[tool.briefcase.app.facemole.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.facemole.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.facemole.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.facemole.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.facemole.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
